name: Manual SonarCloud Analysis

on:
  workflow_dispatch:
    inputs:
      pr_id:
        description: 'Pull Request ID to analyze'
        required: true
        type: string

jobs:
  sonar-analysis:
    name: SonarCloud Analysis for PR
    runs-on: ubuntu-latest

    steps:
      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.pr_id }}
            });
            core.setOutput('head_ref', pr.data.head.ref);
            core.setOutput('base_ref', pr.data.base.ref);
            core.setOutput('head_sha', pr.data.head.sha);

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.head_sha }}
          fetch-depth: 0

      - name: Set up Go 1.24.5
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 8.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -p 1 -v ./... -coverprofile="coverage.out"
        env:
          GO_ENV: test
          MONGODB_URI: mongodb://127.0.0.1:27017
          MONGO_DB: switcher-gitops-test
          GIT_TOKEN_PRIVATE_KEY: ${{ secrets.GIT_TOKEN_PRIVATE_KEY }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_TOKEN_READ_ONLY: ${{ secrets.GIT_TOKEN_READ_ONLY }}
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          GIT_BRANCH: ${{ secrets.GIT_BRANCH }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: env.SONAR_TOKEN != ''
        with:
          args: >
            -Dsonar.pullrequest.key=${{ inputs.pr_id }}
            -Dsonar.pullrequest.branch=${{ steps.pr.outputs.head_ref }}
            -Dsonar.pullrequest.base=${{ steps.pr.outputs.base_ref }}